baseURL: "/"
defaultContentLanguage: "en"
languageCode: en-US
title: "Basajan"
theme: "basajan"
copyright: "Copyright © 2022 - present · John Doe"
sectionPagesMenu: "main"
paginate: 8
summaryLength: 25
enableRobotsTXT: true
disqusShortname: ""
author:
  name: "John Doe"
  image: ""
  email: "hi@husen.id"
  bio: "Written by <strong>John</strong> Doe. This is where your author bio lives. Share everything that you think best describes you."
  social:
    facebook: "johndoe"
    instagram: "johndoe"
    linkedin: "johndoe"
    twitter: "johndoe"
minify:
  _merge: deep
taxonomies:
  _merge: deep
markup:
  _merge: deep
