baseURL: "/"
languageCode: "en"
title: "Basajan"
theme: "basajan"
copyright: "Copyright © 2022 - present · You"
sectionPagesMenu: "main"
paginate: 8
summaryLength: 25
enableRobotsTXT: true
disqusShortname: ""
author:
  name: "You"
  image: "https://i.pravatar.cc/256"
  email: ""
  bio: "Written by <strong>You</strong>. This is where your author bio lives. Share everything that you think best describes you."
  social:
    facebook: "you"
    instagram: "you"
    linkedin: "you"
    twitter: "you"
taxonomies:
  _merge: deep
markup:
  _merge: deep
minify:
  _merge: deep
