[build]
  publish = "exampleSite/public/"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build"

[build.environment]
  HUGO_VERSION = "0.92.2"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[context.production.environment]
	HUGO_BASEURL = "https://basajan.netlify.app/"
	HUGO_DISQUSSHORTNAME = "hugo-themes"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
  debug = true
  srcdir = "exampleSite"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.8
    seo = 0.9
