name = "Basajan"
license = "Apache-2.0"
licenselink = "https://github.com/hapakaien/hugo-themes/blob/main/LICENSE"
description = "A very simple & clean blog theme for Hugo, 0kb JavaScript shipped by default."
homepage = "https://github.com/hapakaien/hugo-themes/tree/main/basajan"
demosite = "https://basajan.netlify.app/"
tags = [blog, responsive, personal, minimal]
features = [simple, clean, fast, tailwindcss]

min_version = "0.92.2"

[author]
  name = "Ahmad Husen"
  homepage = "https://husen.id"
