name: CI - Nyerat

on:
  push:
    branches:
      - "main"
    paths:
      - "nyerat/**"
      - ".github/workflows/nyerat.yml"
    tags:
      - "nyerat/v[0-9].[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
    paths:
      - "nyerat/**"
      - ".github/workflows/nyerat.yml"

env:
  FOLDER: nyerat

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"

      - name: Set up pnpm v6
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.x.x
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 'lts/*'
          cache: "pnpm"
          cache-dependency-path: ${{ env.FOLDER }}/pnpm-lock.yaml

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.92.0"
          extended: true

      - name: Cache Hugo
        uses: actions/cache@v3
        with:
          path: ${{ env.FOLDER }}/exampleSite/resources
          key: ${{ runner.os }}-nyerat-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-nyerat-

      - name: Install dependencies
        run: |
          cd ${{ env.FOLDER }}
          pnpm i --frozen-lockfile

      - name: Run build
        run: |
          cd ${{ env.FOLDER }}
          pnpm build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/nyerat/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.2
        with:
          strip_tag_prefix: "nyerat/v"

      - name: Read changelog
        id: changelog-reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.branch-name.outputs.tag }}
          path: ${{ env.FOLDER }}/CHANGELOG.md

      - name: Create/update release
        uses: ncipollo/release-action@v1
        with:
          tag: nyerat/v${{ steps.changelog-reader.outputs.version }}
          name: nyerat/v${{ steps.changelog-reader.outputs.version }}
          body: ${{ steps.changelog-reader.outputs.changes }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
